services:
  homelabmon:
    image: ghcr.io/dx111ge/homelabmon:0.2.3
    container_name: homelabmon
    network_mode: host
    volumes:
      - "/share/Container/homelabmon:/data"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/:/hostfs:ro"
    command: --ui --scan --bind :9600 --no-auth --site home --peer 192.168.178.45:9600 --peer 192.168.178.44:9600
    restart: unless-stopped
